default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  timeout: 5000


development:
  <<: *default
  database: gallery_development

test:
  <<: *default
  database: gallery_test

production:
  <<: *default
  database: gallery_production
